### PR TITLE
Update initrd & vmlinuz urls

### PR DESCRIPTION
**Pull request by laithshadeed**

### CODE REVIEW

**Comment by felixsanz** [comment]
Don't accept this PR please. The latest version doesn't work anymore. Latest compatible version is 0.7.1, so the version flag must be an option

**Comment by robbertkl** [comment]
I'm away on vacation atm, so I only quickly glanced at this PR and that's the first thing I thought: it breaks the version flag.

What do you mean "latest compatible version"? My script probably doesn't work anymore, since RancherOS has a new (rewritten?) installer for v0.8.0. I'll test it again soon and make some changes for this procedure, based on the new installer. Although a PR for this (i.e. v0.8.0 compatibility) is very welcome as well...

**Comment by felixsanz** [comment]
@robbertkl Do you think 0.8.0 will ever work? because you have to boot using the rancherOS ISO. installation from finnix not available anymore

**Comment by laithshadeed** [comment]
mm. I did not notice that. You guys have a valid point. I will check it out tonight and update the PR. Cheers

**Comment by Snake4life** [comment]
any news on 0.9.0?

**Comment by robbertkl** [comment]
@felixsanz @Snake4life I've just did an install (RancherOS v1.1.0) and it still seems to work just fine. I was worried you might need to boot from the ISO (which is not directly possible), but it turns out the install still works the old way.

The fixes in my install.sh might not do exactly the right thing anymore, but the end result is still a working system.

As an alternative, I installed RancherOS using [Linode's Custom Distrubution guide](https://www.linode.com/docs/tools-reference/custom-kernels-distros/install-a-custom-distribution-on-a-linode), which also worked.

Closing this PR.

**Pull request closed without merging**
